### ISSUE TITLE
Not possible to use Strava API with read-only scope

### ISSUE THREAD

**Issue by jwellner** [SocialiteProviders/Strava#1]
With the Strava API you can get read-only permission by *not* providing a scope.

The problem is that socialite always puts a scope parameter in the authorization url.  It creates a URL with an empty scope parameter: https://www.strava.com/oauth/authorize?client_id=XX&redirect_uri=XX&scope=&state=XX

This results in the following error from the Strava API: 

`{"message":"Bad Request","errors":[{"resource":"Authorize","field":"scope","code":"invalid"}]}`

Is possible to remove the scope parameter from the authorization url when it is not provided?

**Comment by DraperStudio** [comment]
You could overwrite the `getCodeFields` method and remove the scopes field. The function can be found here https://github.com/laravel/socialite/blob/8f611b9135eac1a82235dac9b6c2f3c864489372/src/Two/AbstractProvider.php and would need to be overridden in the Provider.php of the Strava Provider.
